const score = 400
console.log(score);

const balance = new Number(100)
console,log(balance);

console.log(balance.toString().length);
console.log(balance.toFixed(1));

const otherNumber = 1123.8966

console.log(otherNumber.toPrecision(3));

const hundreds = 1000000
console.log(hundreds.toLocaleString('en-IN'));



// ++++++++++++++++++++++++++++ MATHS ++++++++++++++++++++++++++++++++++++++++++++

console.log(Math);
console.log(Math.abs(-4)); //returns absolute value
console.log(Math.round(4.6)); // returns the rounded off vlue
console.log(Math.ceil(4.6));
console.log(Math.floor(4.6)); 
console.log(Math.min(4,6,8));

console.log(Math.random()); //generates random numbers between 0 and 1
console.log((Math.random()*10)+1); // makes sure that 0 is not generated by the floor func in cases like 0.1 etc 1 is added
console.log(Math.floor(Math.random()*10)+1);// returns single digit from 1-9

const min = 10
const max = 20

console.log(Math.floor(Math.random() * (max - min + 1)) + min); // Same thing that is happening above is done in the range of max and min


